// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv73FFhHsq4WTb0kCJEZOuR3qvJG1gK_k',
    appId: '1:787301430866:web:6372e2d3f7385b34fd518b',
    messagingSenderId: '787301430866',
    projectId: 'flutter-firebase-6c3f1',
    authDomain: 'flutter-firebase-6c3f1.firebaseapp.com',
    storageBucket: 'flutter-firebase-6c3f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJuBWT1mtSp6kdPpnaEGGA1V6HYejlufQ',
    appId: '1:787301430866:android:20c1eba816476ea2fd518b',
    messagingSenderId: '787301430866',
    projectId: 'flutter-firebase-6c3f1',
    storageBucket: 'flutter-firebase-6c3f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTdlmRfgTTiXrQJuZntYZPiF2hMYHzia8',
    appId: '1:787301430866:ios:4ea86687ef9ee3c3fd518b',
    messagingSenderId: '787301430866',
    projectId: 'flutter-firebase-6c3f1',
    storageBucket: 'flutter-firebase-6c3f1.appspot.com',
    iosClientId: '787301430866-bdt5ddmhctitlroe7hbl8tuhak9jie00.apps.googleusercontent.com',
    iosBundleId: 'com.berkayozbuga.flutterFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTdlmRfgTTiXrQJuZntYZPiF2hMYHzia8',
    appId: '1:787301430866:ios:4ea86687ef9ee3c3fd518b',
    messagingSenderId: '787301430866',
    projectId: 'flutter-firebase-6c3f1',
    storageBucket: 'flutter-firebase-6c3f1.appspot.com',
    iosClientId: '787301430866-bdt5ddmhctitlroe7hbl8tuhak9jie00.apps.googleusercontent.com',
    iosBundleId: 'com.berkayozbuga.flutterFirestore',
  );
}
